## Project 4
### Brenden Latham, Ashish Yonzon, Oluwatobi Afolabi
### CPSMA-4413
### Dr. Jacob

In this project we will be performing some Gauss-Jordan elimination. I will first make some functions and go through it manually

In [195]:
import math
import numpy as np

In [196]:
#swaps row1 and row2 in matrix A
def swap(row1, row2, A):
  temp_vec = []
  temp_vec = A[row1]
  A[row1] = A[row2]
  A[row2] = temp_vec
  return(A)
#adds row1 to row2 in matrix A
def add(row1, row2, A):
  for i in range(len(A[row1])):
     A[row1][i] = A[row1][i]+A[row2][i]
  return(A)

# multiplies row1 by a constant c in matrix A
def multiply(row1, c, A):
  for i in range(len(A[row1])):
    A[row1][i] = c*A[row1][i]
  return(A)

# checks to see if the matrix is square. returns boolean
def test_square(A):
  square = True
  for i in range(len(A)):
    if len(A) != len(A[i]):
      square = False
  return(square)

Now that the functions are made, let's solve a system.

In [105]:
A = [[1,1,3],[3,2,1],[2,1,2]]
b = [[2],[1],[3]]
A = np.concatenate((A, b), axis=1, dtype=float)
print(A,"\n")

A = multiply(0,-3,A)
A = add(1,0,A)
A = multiply(0,-1/3,A)
print(A,"\n")

A = multiply(0,-2,A)
A = add(2,0,A)
A = multiply(0,-1/2,A)
print(A,"\n")

A = multiply(1,-1,A)
print(A,"\n")

A = add(2,1,A)
print(A,"\n")

A = multiply(2,1/4,A)
print(A,"\n")

A = multiply(2,-8,A)
A = add(1,2,A)
A = multiply(2,-1/8,A)
print(A,"\n")

A = multiply(2,-3,A)
A = add(0,2,A)
A = multiply(2,-1/3,A)
print(A,"\n")

A = multiply(1,-1,A)
A = add(0,1,A)
A = multiply(1,-1,A)
print(A,"\n")

[[1. 1. 3. 2.]
 [3. 2. 1. 1.]
 [2. 1. 2. 3.]] 

[[ 1.  1.  3.  2.]
 [ 0. -1. -8. -5.]
 [ 2.  1.  2.  3.]] 

[[ 1.  1.  3.  2.]
 [ 0. -1. -8. -5.]
 [ 0. -1. -4. -1.]] 

[[ 1.  1.  3.  2.]
 [-0.  1.  8.  5.]
 [ 0. -1. -4. -1.]] 

[[ 1.  1.  3.  2.]
 [-0.  1.  8.  5.]
 [ 0.  0.  4.  4.]] 

[[ 1.  1.  3.  2.]
 [-0.  1.  8.  5.]
 [ 0.  0.  1.  1.]] 

[[ 1.  1.  3.  2.]
 [-0.  1.  0. -3.]
 [ 0.  0.  1.  1.]] 

[[ 1.  1.  0. -1.]
 [-0.  1.  0. -3.]
 [ 0.  0.  1.  1.]] 

[[ 1.  0.  0.  2.]
 [-0.  1.  0. -3.]
 [ 0.  0.  1.  1.]] 



It seems our functions work, however this isnt very computer sciency of us. Let's automate the process.

In [193]:
def Gauss_elim(A, b):
  augmented = np.concatenate((A, b), axis=1, dtype=float)
  i = 0
  j = i-1
  #forward
  while i < len(b):
    for j in range(i+1, len(b)):
      factor = augmented[j][i]/augmented[i][i]
      augmented[j] = augmented[j] - (factor*augmented[i])
      print(augmented,"\n")
    i = i+1
  #cleaning
  for k in range(len(b)-1, -1, -1):
    augmented[k] = augmented[k]/augmented[k][k]
    print(augmented,"\n")
  #backward
  for k in range(len(b)-2, -1, -1):
    for l in range(k+1, len(b)):
      factor = augmented[k][l]
      augmented[k] = augmented[k]-(factor*augmented[l])
      print(augmented,"\n")

Now to test it out on the same system.

In [197]:
mat = np.array([[1,1,3],[3,2,1],[2,1,2]])
sol = np.array([[2],[1],[3]])

Gauss_elim(mat,sol)

[[ 1.  1.  3.  2.]
 [ 0. -1. -8. -5.]
 [ 2.  1.  2.  3.]] 

[[ 1.  1.  3.  2.]
 [ 0. -1. -8. -5.]
 [ 0. -1. -4. -1.]] 

[[ 1.  1.  3.  2.]
 [ 0. -1. -8. -5.]
 [ 0.  0.  4.  4.]] 

[[ 1.  1.  3.  2.]
 [ 0. -1. -8. -5.]
 [ 0.  0.  1.  1.]] 

[[ 1.  1.  3.  2.]
 [-0.  1.  8.  5.]
 [ 0.  0.  1.  1.]] 

[[ 1.  1.  3.  2.]
 [-0.  1.  8.  5.]
 [ 0.  0.  1.  1.]] 

[[ 1.  1.  3.  2.]
 [-0.  1.  0. -3.]
 [ 0.  0.  1.  1.]] 

[[ 1.  0.  3.  5.]
 [-0.  1.  0. -3.]
 [ 0.  0.  1.  1.]] 

[[ 1.  0.  0.  2.]
 [-0.  1.  0. -3.]
 [ 0.  0.  1.  1.]] 



It looks like it worked. This method is nice, however our specific implementation of it has flaws. I believe we would have a problem if the diagonal on our system contained a zero. To account for this, we would have to implore methods out of the scope of this project. This method would be doing work on the pivot points to eliminate the possibility of division by zero.

As a last illustration of another flaw in our code we will look at an interesting system

In [199]:
B = [[1,-2],[2,-4]]
c = [[2],[4]]
Gauss_elim(B,c)

[[ 1. -2.  2.]
 [ 0.  0.  0.]] 

[[ 1. -2.  2.]
 [nan nan nan]] 

[[ 1. -2.  2.]
 [nan nan nan]] 

[[nan nan nan]
 [nan nan nan]] 



<ipython-input-193-dd53fe1ffdbe>:14: RuntimeWarning: invalid value encountered in true_divide
  augmented[k] = augmented[k]/augmented[k][k]


The geometric interpretation of the system we used is two parallel lines. Because these lines are parallel, they will cross at no points, and there is no solution for the system. A professional implementation of Gauss-Jordan elimination would also account for this by outputing a message such as "no solution" to the user.